import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { BsChevronLeft, BsPlus } from "react-icons/bs";
import { Table } from "~/components/table";
import { env } from "~/env.mjs";
import { withSessionSsr } from "~/server/session";

const Products: NextPage = () => {
  return (
    <>
      <Head>
        <title>{"Products " + env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-4">
        <div className="flex justify-between">
          <Link href="/admin/products/create" className="btn gap-2">
            <BsPlus className="h-6 w-6" />
            Create
          </Link>
          <div className="btn-group">
            <button className="btn-outline btn">
              <BsChevronLeft className="h-4 w-4" />
            </button>
            <button className="btn">Next page</button>
          </div>
        </div>

        <Table></Table>
      </div>
    </>
  );
};

export const getServerSideProps = withSessionSsr(({ req }) => {
  const { authId } = req.session;

  if (!authId) {
    return {
      redirect: {
        permanent: false,
        destination: "/admin",
      },
    };
  }

  return {
    props: {},
  };
});

export default Products;
