import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { CarCard } from "~/components/car-card";
import { Hero } from "~/components/hero";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero /> */}
      {products.map((product, i) => (
        <CarCard value={product} key={i} />
      ))}
    </>
  );
};

export default Home;

const products = [
  {
    id: 3,
    make: "Mercedes",
    model: "CLK63",
    image:
      "https://media.autoexpress.co.uk/image/private/s--PdDCOpWt--/v1660580994/evo/2022/08/MercedesBenz%20CLK63%20AMG%20Black%20Series%20icon-15.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, explicabo. In ex expedita velit, odit animi quidem! Hic quae atque molestias, voluptatem explicabo, a libero tempore officiis non eius temporibus!",
    year: 2014,
    mileage: 48230,
    engineSize: 2,
    fuel: "diesel",
    transmission: "manual",
    price: 17999,
  },
];
